apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: mh17665/password:1.0
        command: ["python","test.py"]
      restartPolicy: Never
  backoffLimit: 4
